### ISSUE TITLE
dts-gen fails on exiftool-vendored

### ISSUE THREAD

**Issue by r351574nc3** [Microsoft/dts-gen#102]
Full command and stacktrace
```
dts-gen -m exiftool-vendored                                                   ⏎ ✭ ✖ ✱ ◼
Unexpected crash! Please log a bug with the commandline you specified.
/usr/local/lib/node_modules/dts-gen/bin/lib/run.js:130
        throw e;
        ^

TypeError: Cannot read property 'ended' of undefined
    at Object.get [as ended] (/Users/leoprzybylski/src/github.com/r351574nc3/steem-bot-examples/steem-exif-spider-bot/node_modules/exiftool-vendored/dist/ExifTool.js:193:38)
    at getProperty (/usr/local/lib/node_modules/dts-gen/bin/lib/index.js:254:30)
    at Array.map (<anonymous>)
    at getPropertyDeclarationsOfObject (/usr/local/lib/node_modules/dts-gen/bin/lib/index.js:250:25)
    at getTypeOfValue (/usr/local/lib/node_modules/dts-gen/bin/lib/index.js:237:33)
    at getResult (/usr/local/lib/node_modules/dts-gen/bin/lib/index.js:173:32)
    at getTopLevelDeclarations (/usr/local/lib/node_modules/dts-gen/bin/lib/index.js:123:17)
    at getResult (/usr/local/lib/node_modules/dts-gen/bin/lib/index.js:148:17)
    at getTopLevelDeclarations (/usr/local/lib/node_modules/dts-gen/bin/lib/index.js:123:17)
    at getResult (/usr/local/lib/node_modules/dts-gen/bin/lib/index.js:191:35)
```

**Comment by indusbull** [comment]
I am running into same crash error but with dmn-js module. 

```
dts-gen -m dmn-js                                                                                                      
Unexpected crash! Please log a bug with the commandline you specified.                                                                                                                      
C:\Users\user1\AppData\Roaming\npm\node_modules\dmn-js\index.js:1                                                                                                                         
(function (exports, require, module, __filename, __dirname) { export { default } from './lib/Viewer';                                                                                       
                                                              ^^^^^^                                                                                                                        
SyntaxError: Unexpected token export                                                                                                                                                        
    at Object.exports.runInThisContext (vm.js:78:16)                                                                                                                                        
    at Module._compile (module.js:543:28)                                                                                                                                                   
    at Object.Module._extensions..js (module.js:580:10)                                                                                                                                     
    at Module.load (module.js:488:32)                                                                                                                                                       
    at tryModuleLoad (module.js:447:12)                                                                                                                                                     
    at Function.Module._load (module.js:439:3)                                                                                                                                              
    at Module.require (module.js:498:17)                                                                                                                                                    
    at require (internal/module.js:20:19)                                                                                                                                                   
    at Object.<anonymous> (C:\Users\v160771\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\run.js:57:67)                                                                                  
    at Module._compile (module.js:571:32)  
```
