### ISSUE TITLE
Unexpected crash! - @google-cloud/compute

### ISSUE THREAD

**Issue by welkie** [Microsoft/dts-gen#103]
I got this error message when trying to generate types for the `@google-cloud/compute` package:

```
$ dts-gen -m @google-cloud/compute

Unexpected crash! Please log a bug with the commandline you specified.
/home/mwelke/.config/yarn/global/node_modules/dts-gen/bin/lib/run.js:130
        throw e;
        ^

Error: ENOENT: no such file or directory, open '@google-cloud/compute.d.ts'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1291:33)
    at Object.<anonymous> (/home/mwelke/.config/yarn/global/node_modules/dts-gen/bin/lib/run.js:112:12)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
```

My first suspicion was that this was an issue with me using Yarn instead of NPM, so I tried generating types for the `yargs` package in the readme example. That actually worked fine:

```
$ dts-gen -m yargs
Wrote 141 lines to yargs.d.ts.
```

In both cases, I made sure to install the packages globally as per the readme instructions before running the `dts-gen` command to generate types for them.

Could this be an issue with this particular package?

My info:

@google-cloud/compute version: 0.10.0
yarn version: 1.5.1
Node version: 8.9.4

**Comment by Naatan** [comment]
Seems the problem is the forward slash, you can work around the issue by manually specifying the output file with `-f`/

**Comment by Naatan** [comment]
I actually got the same thing, thought that's a different issue than the one that was initially reported here.

Is this project still supported? The original issue was reported 15 days ago and it has yet to receive a response.

**Comment by carlos-bernal-gby** [comment]
Had the same problem but with the `@google-cloud/bigquery` module. I've opened a new issue [#107](https://github.com/Microsoft/dts-gen/issues/107) describing that a `d.ts` file is generated but the content doesn't make sense.

**Comment by yanniks** [comment]
Any updates on this?
