### ISSUE TITLE
dts-gen -m fs --stdout  example results in Unexpected crash! 

### ISSUE THREAD

**Issue by denisbetsi** [microsoft/dts-gen#108]
dts-gen -m fs --stdout
Unexpected crash! Please log a bug with the commandline you specified.
/usr/local/lib/node_modules/dts-gen/bin/lib/run.js:130
        throw e;
        ^

TypeError: Cannot read property 'flowing' of undefined
    at Readable.get (_stream_readable.js:953:32)
    at getProperty (/usr/local/lib/node_modules/dts-gen/bin/lib/index.js:254:30)
    at Array.map (<anonymous>)
    at getPropertyDeclarationsOfObject (/usr/local/lib/node_modules/dts-gen/bin/lib/index.js:250:25)
    at getTypeOfValue (/usr/local/lib/node_modules/dts-gen/bin/lib/index.js:237:33)
    at getResult (/usr/local/lib/node_modules/dts-gen/bin/lib/index.js:173:32)
    at getTopLevelDeclarations (/usr/local/lib/node_modules/dts-gen/bin/lib/index.js:123:17)
    at getResult (/usr/local/lib/node_modules/dts-gen/bin/lib/index.js:148:17)
    at getTopLevelDeclarations (/usr/local/lib/node_modules/dts-gen/bin/lib/index.js:123:17)
    at getResult (/usr/local/lib/node_modules/dts-gen/bin/lib/index.js:191:35)

npm --version
6.0.1

tsc --version
Version 2.9.1

npm --version
6.0.1

node --version
v9.10.1

OS: 
macOS High Sierra
V 10.13.4

**Comment by sandersn** [comment]
accessing Readable.readableFlowing throws 'TypeError: Cannot read property 'flowing' of undefined.

I guess this is a getter that depends on some other property being set.
