### ISSUE TITLE
Unexpected crash when generating types for `jsforce@1.8.5`

### ISSUE THREAD

**Issue by rodush** [Microsoft/dts-gen#112]
```
Romans-MacBook-Pro:serverless rodush$ yarn dts-gen -m jsforce --dt types/jsforce
yarn run v1.2.1
$ /Users/rodush/web/company/serverless/node_modules/.bin/dts-gen -m jsforce --dt types/jsforce
Unexpected crash! Please log a bug with the commandline you specified.
/Users/rodush/web/company/serverless/node_modules/dts-gen/bin/lib/run.js:130
        throw e;
        ^

TypeError: Cannot read property 'highWaterMark' of undefined
    at module.exports.get (/Users/rodush/web/company/serverless/node_modules/readable-stream/lib/_stream_readable.js:885:32)
    at getProperty (/Users/rodush/web/company/serverless/node_modules/dts-gen/bin/lib/index.js:254:30)
    at Array.map (<anonymous>)
    at getPropertyDeclarationsOfObject (/Users/rodush/web/company/serverless/node_modules/dts-gen/bin/lib/index.js:250:25)
    at getTypeOfValue (/Users/rodush/web/company/serverless/node_modules/dts-gen/bin/lib/index.js:237:33)
    at getResult (/Users/rodush/web/company/serverless/node_modules/dts-gen/bin/lib/index.js:173:32)
    at getTopLevelDeclarations (/Users/rodush/web/company/serverless/node_modules/dts-gen/bin/lib/index.js:123:17)
    at getResult (/Users/rodush/web/company/serverless/node_modules/dts-gen/bin/lib/index.js:148:17)
    at getTopLevelDeclarations (/Users/rodush/web/company/serverless/node_modules/dts-gen/bin/lib/index.js:123:17)
    at getResult (/Users/rodush/web/company/serverless/node_modules/dts-gen/bin/lib/index.js:148:17)
error Command failed with exit code 1.

```

**Comment by namik-hajiyev** [comment]
**dts-gen -m winston-transport  -o -f winston-transport.d.ts**
Unexpected crash! Please log a bug with the commandline you specified.
C:\Users\User\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\run.js:130
        throw e;
        ^

TypeError: Cannot read property 'highWaterMark' of undefined
    at Writable.get (C:\Users\User\AppData\Roaming\npm\node_modules\winston-transport\node_modules\readable-stream\lib\_stream_writable.js:377:32)
    at getProperty (C:\Users\User\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:254:30)
    at Array.map (<anonymous>)
    at getPropertyDeclarationsOfObject (C:\Users\User\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:250:25)
    at getTypeOfValue (C:\Users\User\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:237:33)
    at getResult (C:\Users\User\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:173:32)
    at getTopLevelDeclarations (C:\Users\User\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:123:17)
    at getResult (C:\Users\User\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:148:17)
    at getTopLevelDeclarations (C:\Users\User\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:123:17)
    at Object.generateModuleDeclarationFile (C:\Users\User\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:49:19)

**Comment by namik-hajiyev** [comment]
> ```
> Romans-MacBook-Pro:serverless rodush$ yarn dts-gen -m jsforce --dt types/jsforce
> yarn run v1.2.1
> $ /Users/rodush/web/company/serverless/node_modules/.bin/dts-gen -m jsforce --dt types/jsforce
> Unexpected crash! Please log a bug with the commandline you specified.
> /Users/rodush/web/company/serverless/node_modules/dts-gen/bin/lib/run.js:130
>         throw e;
>         ^
> 
> TypeError: Cannot read property 'highWaterMark' of undefined
>     at module.exports.get (/Users/rodush/web/company/serverless/node_modules/readable-stream/lib/_stream_readable.js:885:32)
>     at getProperty (/Users/rodush/web/company/serverless/node_modules/dts-gen/bin/lib/index.js:254:30)
>     at Array.map (<anonymous>)
>     at getPropertyDeclarationsOfObject (/Users/rodush/web/company/serverless/node_modules/dts-gen/bin/lib/index.js:250:25)
>     at getTypeOfValue (/Users/rodush/web/company/serverless/node_modules/dts-gen/bin/lib/index.js:237:33)
>     at getResult (/Users/rodush/web/company/serverless/node_modules/dts-gen/bin/lib/index.js:173:32)
>     at getTopLevelDeclarations (/Users/rodush/web/company/serverless/node_modules/dts-gen/bin/lib/index.js:123:17)
>     at getResult (/Users/rodush/web/company/serverless/node_modules/dts-gen/bin/lib/index.js:148:17)
>     at getTopLevelDeclarations (/Users/rodush/web/company/serverless/node_modules/dts-gen/bin/lib/index.js:123:17)
>     at getResult (/Users/rodush/web/company/serverless/node_modules/dts-gen/bin/lib/index.js:148:17)
> error Command failed with exit code 1.
> ```

I had that error too. I have used this package to generate types files. https://www.npmjs.com/package/dts-generator
