### ISSUE TITLE
Unexpected crash! Please log a bug with the commandline you specified.

### ISSUE THREAD

**Issue by infrarosso78** [Microsoft/dts-gen#113]
dts-gen -m polymer-redux

(function (exports, require, module, __filename, __dirname) { import {get} from '../@polymer/polymer/lib/utils/path.js';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/dts-gen/bin/lib/run.js:57:67)

**Comment by mrdulin** [comment]
+1

**Comment by GitStorageOne** [comment]
dts-get -m oidc-provider

**Comment by jaxoncreed** [comment]
@GitStorageOne Trying to do the exact same thing. I'll post if I find a solution.
