### ISSUE TITLE
strictFunctionTypes isn't specified

### ISSUE THREAD

**Issue by mtsmfm** [Microsoft/dts-gen#119]
It seems https://github.com/Microsoft/dts-gen/pull/87 isn't applied to the latest release.

https://unpkg.com/dts-gen@0.5.7/bin/lib/definitely-typed.js

```typescript
function getTSConfig(packageName) {
    return {
        compilerOptions: {
            module: "commonjs",
            lib: ["es6"],
            noImplicitAny: true,
            noImplicitThis: true,
            strictNullChecks: true,
            baseUrl: "../",
            typeRoots: ["../"],
            types: [],
            noEmit: true,
            forceConsistentCasingInFileNames: true,
        },
        files: [
            "index.d.ts",
            `${packageName}-tests.ts`,
        ],
    };
}
```

@RyanCavanaugh Can I ask you to cut new release?

**Comment by weswigham** [comment]
@andy-ms ?

**Comment by oBusk** [comment]
When generating brand new package, getting 

```
Error: Expected `"strictFunctionTypes": true` or `"strictFunctionTypes": false`.
    at Object.<anonymous> (/Users/user/DefinitelyTyped/node_modules/dtslint/bin/checks.js:106:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/user/DefinitelyTyped/node_modules/dtslint/bin/checks.js:4:58)
```

on first lint because `dts-gen` does not specify.

**Comment by BendingBender** [comment]
Yeah, it seems that the build wasn't run the last time the package was published.
