### ISSUE TITLE
Unexpected crash! dts-gen -m react-native-jsonschema-form

### ISSUE THREAD

**Issue by jgage176** [Microsoft/dts-gen#131]
```dts-gen -m react-native-jsonschema-form
Unexpected crash! Please log a bug with the commandline you specified.
C:\git\TrackMyDays\TrackMyDaysApp\node_modules\react-native-jsonschema-form\index.js:1
(function (exports, require, module, __filename, __dirname) { import Form from "./components/Form";
                                                                     ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

**Comment by hgezim** [comment]
Got the same issue running `dts-gen -d -m react-native-sectioned-multi-select`:

```
import SectionedMultiSelect from './lib/sectioned-multi-select';
       ^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/dts-gen/bin/lib/run.js:58:67)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
```
