### ISSUE TITLE
Unexpected crash! while Generating from Module

### ISSUE THREAD

**Issue by willyveli** [microsoft/dts-gen#142]
**npm package :** `three`
**command &ensp;&ensp;&ensp;&ensp;:** `dts-gen -m three`
**output &nbsp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;:**

	Unexpected crash! Please log a bug with the commandline you specified.
	node_modules/dts-gen/bin/lib/run.js:125
			throw e;
			^

	TypeError: Cannot read property 'prototype' of undefined
		at isClasslike (node_modules/dts-gen/bin/lib/index.js:114:19)
		at node_modules/dts-gen/bin/lib/index.js:47:41
		at Array.some (<anonymous>)
		at hasCloduleProperties (node_modules/dts-gen/bin/lib/index.js:47:31)
		at getValueTypes (node_modules/dts-gen/bin/lib/index.js:35:37)
		at getResult (node_modules/dts-gen/bin/lib/index.js:192:55)
		at getTopLevelDeclarations (node_modules/dts-gen/bin/lib/index.js:129:17)
		at Object.generateModuleDeclarationFile (node_modules/dts-gen/bin/lib/index.js:55:19)
		at Object.<anonymous> (node_modules/dts-gen/bin/lib/run.js:58:24)
		at Module._compile (internal/modules/cjs/loader.js:936:30)

**Comment by pixelprogrammer** [comment]
I got the same error as well with a different package.

**OS**                 : `Windows 10`
**npm package**: `vue-moveable`
**command**     : `dts-gen -m vue-moveable`
**Terminal/shell**: `powershell` and `git-bash`
**output**          :
```
...\npm\node_modules\dts-gen\bin\lib\run.js:125
        throw e;
        ^

TypeError: Cannot read property 'userAgent' of undefined
    at agent (...\node_modules\vue-moveable\dist\lib\VueMoveable.common.js:2381:100)
    at Module.fb15 (...\node_modules\vue-moveable\dist\lib\VueMoveable.common.js:5277:26)
    at __webpack_require__ (...\node_modules\vue-moveable\dist\lib\VueMoveable.common.js:21:30)
    at ...\node_modules\vue-moveable\dist\lib\VueMoveable.common.js:85:18
    at Object.<anonymous> (...\node_modules\vue-moveable\dist\lib\VueMoveable.common.js:88:10)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

**Comment by pixelprogrammer** [comment]
Looks like browser specific modules will have issues and is still in development. This is at the bottom of their README.md file:

```
Note: Browser support in progress! This is not quite ready yet.
```

Curious if this is the reason for the error.
