### ISSUE TITLE
Crash with scoped package

### ISSUE THREAD

**Issue by martinmcwhorter** [microsoft/dts-gen#153]
I am getting a crash trying to generate definitions for a scoped package. 

The command I run:

`dts-gen -m @commitlint/load`

```Unexpected crash! Please log a bug with the commandline you specified.
/Users/martin.mcwhorter/.nvm/versions/node/v12.6.0/lib/node_modules/dts-gen/bin/lib/run.js:125
        throw e;
        ^

Error: ENOENT: no such file or directory, open '@commitlint/load.d.ts'
    at Object.openSync (fs.js:447:3)
    at Object.writeFileSync (fs.js:1206:35)
    at Object.<anonymous> (/Users/martin.mcwhorter/.nvm/versions/node/v12.6.0/lib/node_modules/dts-gen/bin/lib/run.js:107:12)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '@commitlint/load.d.ts'
}
```

**Comment by Mistic92** [comment]
I have the same issue for dts-gen -m @sfeir/actions-on-google-i18n

**Comment by Mistic92** [comment]
I think this may be related to creating file on Windows. When I used -f my.d.ts it worked

**Comment by Naxos84** [comment]
Im having also the issue when trying to generate for @buffetjs/core

Command: `dts-gen -m @buffetjs/core`

Error-stack: 

```
Unexpected crash! Please log a bug with the commandline you specified.
C:\Users\${username}\AppData\Roaming\nvm\v12.16.0\node_modules\dts-gen\bin\lib\run.js:125
        throw e;
        ^
ReferenceError: window is not defined
    at Object.<anonymous> (C:\${PROJECT_PATH}\node_modules\@buffetjs\core\build\bundle.development.js:10:4)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10) 
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\${PROJECT_PATH}\node_modules\@buffetjs\core\build\index.js:7:20)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10) 
```

Im using windows.
And it could be that it is another issue since I get another stack trace then the issue creator.
But I'm not sure. So I commented here instead of creating a new issue.
