### ISSUE TITLE
ERR_REQUIRE_ESM: Missing ESM Support

### ISSUE THREAD

**Issue by bgausden** [microsoft/dts-gen#156]
`PS D:\git\email-opt-in>  .\node_modules\.bin\dts-gen  -m request-rate-limiter --stdout
Unexpected crash! Please log a bug with the commandline you specified.
D:\git\email-opt-in\node_modules\dts-gen\bin\lib\run.js:125
        throw e;
        ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: D:\git\email-opt-in\node_modules\request-rate-limiter\index.mjs
    at Module.load (internal/modules/cjs/loader.js:970:11)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Module.require (internal/modules/cjs/loader.js:1012:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\git\email-opt-in\node_modules\dts-gen\bin\lib\run.js:58:67)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'ERR_REQUIRE_ESM'
}`

**Comment by euberdeveloper** [comment]
Same for me
