### ISSUE TITLE
Unexpected crash! Please log a bug with the commandline you specified.

### ISSUE THREAD

**Issue by stitze** [microsoft/dts-gen#157]
Try to generate a definition file for http://britecharts.github.io/britecharts via command

`dts-gen -m britecharts 

Unexpected crash! Please log a bug with the commandline you specified.
userpath\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\run.js:125
        throw e;
        ^

ReferenceError: window is not defined
    at Object.<anonymous> (pathtoproject\node_modules\britecharts\dist\bundled\britecharts.min.js:1:204)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (userpath\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\run.js:58:67)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)`

**Comment by stitze** [comment]
Solved it by adding

`var window=window || {};` 

to the top of the file britecharts.min.js and also added 

`var navigator=navigator || {};` 

After that I get I definition file.
