### ISSUE TITLE
`dts-gen -d yargs` crashes

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/dts-gen#19]
```
/home/andy/types/dts-gen/bin/lib/run.js:109
        throw e;
        ^

Error
    at new ArgsError (/home/andy/types/dts-gen/bin/lib/run.js:25:28)
    at Object.<anonymous> (/home/andy/types/dts-gen/bin/lib/run.js:39:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
```

**Comment by andy-ms** [comment]
This appears to be fixed by adding `"target": "es6",` to the `tsconfig.json`.
