### ISSUE TITLE
dts-gen -d -m feathers crashed

### ISSUE THREAD

**Issue by Cedware** [Microsoft/dts-gen#32]
Running the command `dts-gen -d -m feathers` crashed with the following error message:

```
Unexpected crash! Please log a bug with the commandline you specified.
C:\Users\cke\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\run.js:109
        throw e;
        ^

TypeError: Cannot read property 'statusCode' of undefined
    at IncomingMessage.fresh (C:\Users\cke\Documents\Development\DefinitelyTyped\node_modules\express\lib\request.js:450:19)
    at getProperty (C:\Users\cke\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:264:30)
    at Array.map (native)
    at getPropertyDeclarationsOfObject (C:\Users\cke\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:260:23)
    at getResult (C:\Users\cke\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:246:35)
    at getTypeOfValue (C:\Users\cke\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:217:15)
    at getResult (C:\Users\cke\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:177:30)
    at getTopLevelDeclarations (C:\Users\cke\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:126:15)
    at getResult (C:\Users\cke\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:152:17)
    at getTopLevelDeclarations (C:\Users\cke\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:126:15)
```

**Comment by peterennis** [comment]
c:\ae\dts-gen>dts-gen -m svg.js
Wrote 3 lines to svg.js.d.ts.

The 3 lines are:
/** Declaration file generated by dts-gen */

export = svg.js;

**Comment by viktor1190** [comment]
Any new information about this error?

**Comment by mhegazy** [comment]
We need to change the property access for [`obj[k]`](https://github.com/Microsoft/dts-gen/blob/f89568f33da4ca87b001c0c30915951b48aa753f/lib/index.ts#L273) to be `Object.getOwnPropertyDescriptor(obj, k).value`

**Comment by mhegazy** [comment]
PRs welcomed.
