### ISSUE TITLE
Fails for window object

### ISSUE THREAD

**Issue by ilazarte** [Microsoft/dts-gen#39]
Using default instructions, on 'tone' npm module (Tone.js)

**Comment by ilazarte** [comment]
$ dts-gen -m tone                                                                                   
Unexpected crash! Please log a bug with the commandline you specified.                              
C:\Users\ilazarte\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\run.js:109                       
        throw e;                                                                                    
        ^                                                                                           
                                                                                                    
ReferenceError: window is not defined                                                               
    at C:\Users\ilazarte\src\github\etudes\node_modules\tone\build\Tone.js:45:18                    
    at Main (C:\Users\ilazarte\src\github\etudes\node_modules\tone\build\Tone.js:21:10)             
    at C:\Users\ilazarte\src\github\etudes\node_modules\tone\build\Tone.js:32:2                     
    at C:\Users\ilazarte\src\github\etudes\node_modules\tone\build\Tone.js:9:20                     
    at Object.<anonymous> (C:\Users\ilazarte\src\github\etudes\node_modules\tone\build\Tone.js:14:2)
    at Module._compile (module.js:409:26)                                                           
    at Object.Module._extensions..js (module.js:416:10)                                             
    at Module.load (module.js:343:32)                                                               
    at Function.Module._load (module.js:300:12)                                                     
    at Module.require (module.js:353:17)

**Comment by TrabacchinLuigi** [comment]
got same problem here... i was thinking to comment the lane as workaround... but i'm not sure...
