### ISSUE TITLE
not starting after installation

### ISSUE THREAD

**Issue by select** [Microsoft/dts-gen#44]
I installed dts-gen with 
```
sudo npm install -g dts-gen
```

then I ran 
```
dts-gen
```

> Unexpected crash! Please log a bug with the commandline you specified.
> /usr/local/lib/node_modules/dts-gen/bin/lib/run.js:109
>         throw e;
>         ^
> 
> Error
>     at ArgsError.Error (native)
>     at new ArgsError (/usr/local/lib/node_modules/dts-gen/bin/lib/run.js:25:28)
>     at Object.<anonymous> (/usr/local/lib/node_modules/dts-gen/bin/lib/run.js:39:15)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.runMain (module.js:604:10)
>     at run (bootstrap_node.js:394:7)

```
> npm ---version                             
3.10.8
> node --version            
v6.8.1
> cat /etc/issue          
Ubuntu 16.10 \n \l
```

**Comment by bondz** [comment]
@select try `npm i source-map-support`
