### ISSUE TITLE
Unexpected Crash, ReferenceError: window is not defined, dts-gen -m scrollmagic

### ISSUE THREAD

**Issue by phill2mj** [Microsoft/dts-gen#47]
dts-gen -m scrollmagic
Unexpected crash! Please log a bug with the commandline you specified.
/usr/local/lib/node_modules/dts-gen/bin/lib/run.js:120
        throw e;
        ^

ReferenceError: window is not defined
    at /Users/mike/Documents/viewboard/node_modules/scrollmagic/scrollmagic/uncompressed/ScrollMagic.js:37:2
    at /Users/mike/Documents/viewboard/node_modules/scrollmagic/scrollmagic/uncompressed/ScrollMagic.js:22:20
    at Object.<anonymous> (/Users/mike/Documents/viewboard/node_modules/scrollmagic/scrollmagic/uncompressed/ScrollMagic.js:27:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

**Comment by dandv** [comment]
Same here with

```shell
dts-gen -m image-capture                                              4s 
Unexpected crash! Please log a bug with the commandline you specified.
/usr/lib/node_modules/dts-gen/bin/lib/run.js:130
        throw e;
        ^

ReferenceError: window is not defined
    at /usr/lib/node_modules/image-capture/lib/imagecapture.js:62:45
    at Object.defineProperty.value (/usr/lib/node_modules/image-capture/lib/imagecapture.js:5:5)
    at Object.<anonymous> (/usr/lib/node_modules/image-capture/lib/imagecapture.js:13:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

**Comment by JTOne123** [comment]
the same
 
dts-gen -m browser-report
Unexpected crash! Please log a bug with the commandline you specified.
...\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\run.js:130
        throw e;  

  ^

ReferenceError: window is not defined
    at ...\node_modules\browser-report\index.js:478:5
    at Object.<anonymous> (...\node_modules\browser-report\index.js:509:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (...\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\run.js:57:67)

**Comment by smac89** [comment]
I solved this by editing the file which was giving problems and adding the following to the top:

```js
var window=window || {};
```
The generator then worked after this

**Comment by sim-jo** [comment]
@smac89 - Just one thing to add - You need to remove that line after the ts file has been created. If you don'd remove the file webpack/vendors file will complain/fail if a function or field on the 'window' object is referenced. At this point 'window' will be null.

**Comment by easierbycode** [comment]
The above fixed window, but started me down a rabbit hole of undefined navigator, document, Event, etc..

Here's fix that finally worked (add to top of file):

```
const jsdom = require('jsdom');
const { JSDOM } = jsdom;
const { window } = new JSDOM(``);
const { document, navigator } = window;
```

**Comment by wenfangcao** [comment]
good~thanks!

**Comment by ifiokjr** [comment]
If anyone is still having issues with this I took @easierbycode instructions and created a gist.

https://gist.github.com/ifiokjr/0e1e993f87a8f99b4924e8ecdce0edbc

The problem I was bumping into was 
- `SecurityError: localStorage is not available for opaque origins`

The fix is shown below:

```js
const { JSDOM } = require('jsdom');
const DEFAULT_HTML = '<html><body></body></html>';
const jsdom = new JSDOM(DEFAULT_HTML, {
    url: "https://www.bbc.co.uk",
    referrer: "https://www.bbc.co.uk",
    contentType: "text/html",
    userAgent: "node.js",
    includeNodeLocations: true
});
const { window } = jsdom;
const { document, navigator } = window;
```

**Comment by ststeiger** [comment]
I would say this is smarter:

```
const Window = require('window');
const window = new Window();
const navigator = require('navigator');

const { JSDOM } = require('jsdom');
const DEFAULT_HTML = '<html><body></body></html>';
const jsdom = new JSDOM(DEFAULT_HTML, {
    url: "https://www.bbc.co.uk",
    referrer: "https://www.bbc.co.uk",
    contentType: "text/html",
    userAgent: "node.js",
    includeNodeLocations: true
});
const document = jsdom.window.document;
```
