### ISSUE TITLE
Unexpected Crash mongo-models

### ISSUE THREAD

**Issue by trainerbill** [Microsoft/dts-gen#73]
```
dts-gen --dt --module mongo-models
Unexpected crash! Please log a bug with the commandline you specified.
/home/athroener/.nvm/versions/node/v8.1.0/lib/node_modules/dts-gen/bin/lib/run.js:130
        throw e;
        ^

TypeError: Cannot read property '3' of undefined
    at Object.get [as generationTime] (/home/athroener/.nvm/versions/node/v8.1.0/lib/node_modules/mongodb/node_modules/bson/lib/bson/objectid.js:346:20)
    at getProperty (/home/athroener/.nvm/versions/node/v8.1.0/lib/node_modules/dts-gen/bin/lib/index.js:254:30)
    at Array.map (native)
    at getPropertyDeclarationsOfObject (/home/athroener/.nvm/versions/node/v8.1.0/lib/node_modules/dts-gen/bin/lib/index.js:250:25)
    at getTypeOfValue (/home/athroener/.nvm/versions/node/v8.1.0/lib/node_modules/dts-gen/bin/lib/index.js:237:33)
    at getResult (/home/athroener/.nvm/versions/node/v8.1.0/lib/node_modules/dts-gen/bin/lib/index.js:173:32)
    at getTopLevelDeclarations (/home/athroener/.nvm/versions/node/v8.1.0/lib/node_modules/dts-gen/bin/lib/index.js:123:17)
    at getResult (/home/athroener/.nvm/versions/node/v8.1.0/lib/node_modules/dts-gen/bin/lib/index.js:148:17)
    at getTopLevelDeclarations (/home/athroener/.nvm/versions/node/v8.1.0/lib/node_modules/dts-gen/bin/lib/index.js:123:17)
    at getResult (/home/athroener/.nvm/versions/node/v8.1.0/lib/node_modules/dts-gen/bin/lib/index.js:148:17)
```

**Comment by pinkkis** [comment]
Got the same error in bson package, trying to generate for Mongoist
