### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by oguennec** [Microsoft/dts-gen#81]
> dts-gen --version
0.5.6

> "react-native-fetch-mock": "^0.2.0"

`dts-gen -m react-native-fetch-mock`
Unexpected crash! Please log a bug with the commandline you specified.
/Users/guenneco/react-native/bg-mobile-nga/node_modules/react-native-fetch-mock/src/index.js:1
(function (exports, require, module, __filename, __dirname) { import { parseRequest, matchUrl } from './util';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/guenneco/react-native/bg-mobile-nga/node_modules/react-native-fetch-mock/index.js:1:80)

**Comment by brunolemos** [comment]
#42
