### ISSUE TITLE
Unexpected crash: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by wedi** [Microsoft/dts-gen#83]
Hi,
I am experiencing an "Unexpected crash". Here is what I did:

```
> npm install -g dts-gen
> npm install -g vue2-dropzone
> dts-gen -m vue2-dropzone
```
and this is the result:
```
```
Unexpected crash! Please log a bug with the commandline you specified.
C:\Users\dirk\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\run.js:130
        throw e;
        ^

ReferenceError: window is not defined
    at C:\Users\dirk\AppData\Roaming\npm\node_modules\vue2-dropzone\dist\vue2-dropzone.js:2:24488
    at C:\Users\dirk\AppData\Roaming\npm\node_modules\vue2-dropzone\dist\vue2-dropzone.js:2:24420
    at e.exports (C:\Users\dirk\AppData\Roaming\npm\node_modules\vue2-dropzone\dist\vue2-dropzone.js:2:24706)
    at Object.e.exports.e.webpackPolyfill.e.deprecate (C:\Users\dirk\AppData\Roaming\npm\node_modules\vue2-dropzone\dist\vue2-dropzone.js:2:25182)
    at t (C:\Users\dirk\AppData\Roaming\npm\node_modules\vue2-dropzone\dist\vue2-dropzone.js:1:404)
    at Object.e.exports.e (C:\Users\dirk\AppData\Roaming\npm\node_modules\vue2-dropzone\dist\vue2-dropzone.js:1:527)
    at t (C:\Users\dirk\AppData\Roaming\npm\node_modules\vue2-dropzone\dist\vue2-dropzone.js:1:404)
    at r (C:\Users\dirk\AppData\Roaming\npm\node_modules\vue2-dropzone\dist\vue2-dropzone.js:1:491)
    at C:\Users\dirk\AppData\Roaming\npm\node_modules\vue2-dropzone\dist\vue2-dropzone.js:1:496
    at i.(anonymous function).exports (C:\Users\dirk\AppData\Roaming\npm\node_modules\vue2-dropzone\dist\vue2-dropzone.js:1:143)
```

**Comment by aolney** [comment]
Also had this error. Looks like the problem is that `window` [is browser side](https://stackoverflow.com/questions/14164505/javascript-window-is-not-defined). The README for `dts-gen` has a rather cryptic addendum at the bottom that worked for me with `p5`. Open a page that has the code running that you care about, open the developer console, paste this into console `var s = document.createElement('script'); s.src = 'https://unpkg.com/dts-gen/bin/browser-bundle.js'; document.body.appendChild(s);`, and then type in the name of the type you want to generate a definition for (in my case, `p5`).

**Comment by Nyconing** [comment]
Can you please giving more example on browser-side generation? What is `p5`? Is it `window.p5`? But out put `declare const window.foo: any;`

**Comment by stereobooster** [comment]
```
dts-gen -m leaflet-freedraw
Unexpected crash! Please log a bug with the commandline you specified.
/usr/local/lib/node_modules/dts-gen/bin/lib/run.js:125
        throw e;
        ^

ReferenceError: window is not defined
```

**Comment by zhenwei12138** [comment]
How to generate private package?
