### ISSUE TITLE
Unexpected Crash! adal-node

### ISSUE THREAD

**Issue by benrr101** [Microsoft/dts-gen#84]
When running:
```
> npm install -g dts-gen
> npm install -g adal-node
> dts-gen -m adal-node
```
I got:
```
Unexpected crash! Please log a bug with the commandline you specified.
C:\Users\beruss\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\run.js:130
        throw e;
        ^

TypeError: Cannot read property 'url' of undefined
    at AuthenticationContext.get (C:\Users\beruss\AppData\Roaming\npm\node_modules\adal-node\lib\authentication-context.js:109:27)
    at getProperty (C:\Users\beruss\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:254:30)
    at Array.map (native)
    at getPropertyDeclarationsOfObject (C:\Users\beruss\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:250:25)
    at getTypeOfValue (C:\Users\beruss\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:237:33)
    at getResult (C:\Users\beruss\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:173:32)
    at getTopLevelDeclarations (C:\Users\beruss\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:123:17)
    at getResult (C:\Users\beruss\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:148:17)
    at getTopLevelDeclarations (C:\Users\beruss\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:123:17)
    at getResult (C:\Users\beruss\AppData\Roaming\npm\node_modules\dts-gen\bin\lib\index.js:191:35)
```

**Comment by StarsoftAnalysis** [comment]
This seems to be similar:

    npm install -g dts-gen
    npm install -s block-ui
    dts-gen -m block-ui

results in 

    Unexpected crash! Please log a bug with the commandline you specified.
    /home/chris/npm-global/lib/node_modules/dts-gen/bin/lib/run.js:130
            throw e;
            ^
    TypeError: Cannot read property 'fadeIn' of undefined
        at setup (/home/chris/stasys/dev.ts/node_modules/block-ui/jquery.blockUI.js:20:22)
        at /home/chris/stasys/dev.ts/node_modules/block-ui/jquery.blockUI.js:619:3
        at Object.<anonymous> (/home/chris/stasys/dev.ts/node_modules/block-ui/jquery.blockUI.js:625:3)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
