### ISSUE TITLE
Unexpected crash > dts-gen -d node-red -m node-red

### ISSUE THREAD

**Issue by andersea** [Microsoft/dts-gen#85]
Hi. I am trying to generate typings for [Node-RED](https://nodered.org/).

I get a crash. Here is the printout -
```bash
andersa@Kubuntu:~/nodejs$ dts-gen -d node-red -m node-red
Deprecated use of RED.app - use RED.httpAdmin instead
Deprecated use of RED.app - use RED.httpAdmin instead
Deprecated use of RED.app - use RED.httpAdmin instead
Deprecated use of RED.app - use RED.httpAdmin instead
Unexpected crash! Please log a bug with the commandline you specified.
/home/andersa/.npm-global/lib/node_modules/dts-gen/bin/lib/run.js:130
        throw e;
        ^

Error: ENOENT: no such file or directory, mkdir 'types/node-red'
    at Object.fs.mkdirSync (fs.js:892:18)
    at Object.writeDefinitelyTypedPackage [as default] (/home/andersa/.npm-global/lib/node_modules/dts-gen/bin/lib/definitely-typed.js:24:14)
    at Object.<anonymous> (/home/andersa/.npm-global/lib/node_modules/dts-gen/bin/lib/run.js:92:35)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
```

**Comment by andersea** [comment]
I have found the cause of this.

The error occurs in `lib/definitely-typed.ts`.

```javascript
export default function writeDefinitelyTypedPackage(
		indexDtsContent: string, packageName: string, overwrite: boolean): void {
	const packageDir = joinPaths("types", packageName);

	// Check for overwrite
	if (!overwrite) {
		if (existsSync(packageDir)) {
			console.log(`Directory ${packageDir} already exists and -overwrite was not specified; exiting.`);
			process.exit(2);
		}
	}

	if (!existsSync(packageDir)) {
		mkdirSync(packageDir); <<-- Can't create nested directories (on linux).
	}

	run(indexDtsContent, packageName, packageDir).catch(e => {
		console.error(e);
		process.exit(1);
	});
}
```

The code expects dts-gen to be run from the DefinitelyTyped root directory, so it expects that the types directory already exists, when it doesn't, mkdir fails because it can't create nested directory structures.


I don't think this is the best assumption to make. From my perspective, trying to create my first type definition file and just testing things out, I probably do not want to mess with the entire DefinitelyTyped repository yet. I just want a directory with the necessary files created.

For now, I can work around this by creating the types directory manually and running the command from the directory above.

**Comment by kylegoetz** [comment]
Anyone know a workaround? I'm trying to make my first types package for a pre-existing lib and cannot for the life of me figure out how to get it to work: @DefinitelyTyped/issues/30208 is where I put my first issue regarding this.

**Comment by rahbal** [comment]
I am doing this. I have same concern as @kylegoetz . 
Any suggestions , how do I do it for the local node_modules directory ?
