### ISSUE TITLE
dts-gen -m angularfire

### ISSUE THREAD

**Issue by suni619** [Microsoft/dts-gen#9]
Unexpected crash! Please log a bug with the commandline you specified.
/usr/local/lib/node_modules/dts-gen/bin/lib/run.js:107
        throw e;
        ^

ReferenceError: window is not defined
    at Object.<anonymous> (/usr/local/lib/node_modules/angular/angular.js:31766:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/angular/index.js:1:63)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by sherif2016** [comment]
Facing same problem while generating for angular-material-data-table
Struggling for 2 weeks with this.

Any help greatly appreciated!

PS: I wrote to support team, haven't heard anything yet.

**Comment by aristotll** [comment]
Facing same problem while generating for module **avalon2**
