### ISSUE TITLE
Unexpected crash when generating typings for DefinitelyTyped

### ISSUE THREAD

**Issue by cfguimaraes** [Microsoft/dts-gen#97]
When I run
`dts-gen -m kinto -d `
I've ran into

```
/usr/lib/node_modules/dts-gen/bin/lib/run.js:130
        throw e;
        ^

Error: ENOENT: no such file or directory, mkdir 'types/kinto'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:924:18)
    at Object.writeDefinitelyTypedPackage [as default] (/usr/lib/node_modules/dts-gen/bin/lib/definitely-typed.js:24:14)
    at Object.<anonymous> (/usr/lib/node_modules/dts-gen/bin/lib/run.js:92:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

I've inspected and discovered that this bug only occurs if the directory types/kinto doesn't exist
I've created manually these directories and run again the command and all work fine.
If the existence of the directory is required I think that it has to be better documented, and, in this way, I can do this.

**Comment by DetachHead** [comment]
duplicate of #85
